### PR TITLE
adds Terraform Operator

### PR DESCRIPTION
**Pull request by ksatirli**
This PR adds code for the Terraform Operator and ensures the right Terraform version is used.

@redeux and I both worked on this, so hoping @onlydole / @tracypholmes can review this!

### CODE REVIEW

**Comment by tracypholmes** [comment]
Is it working?! 😄

**Comment by redeux** [comment]
Yep!

**Review by tracypholmes — APPROVED** [review]
LGTM!

**Comment by ksatirli** [comment]
Thank you!

**Pull request merged**
